---
- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files:
    - vars/common.yaml
    - vars/newslynx-core.yaml
    - vars/newslynx-app.yaml
    - vars/postgres.yaml

  tasks:

    # Common apt packages
    - name: Install common apt packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - git
        - gcc 
        - supervisor
        - htop
        - jq
        - ansible
        - make
      sudo: yes

    # directory structure
    - name: ensure the root directory exists
      file: "state=directory path={{home}} mode=0700"

    - name: ensure the scripts directory exists
      file: "state=directory path={{home}}/scripts mode=0700"

    # Roles
    - include: newslynx-core.yaml
    - include: newslynx-app.yaml

