---
- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files:
    - vars/main.yaml

  # install postgres and postgis, mount a disk, change the data directory
  tasks:

    # SYS REQUIREMENTS

    - name: Install apt packages
      apt: name={{item}} state=present update_cache=yes
      with_items: apt_packages 

    # NEWSLYNX-CORE

    - name: ensure the root directory EXISTS
      file: "state=directory path={{root_dir}} mode=0777"

    - name: Clone newslynx-repos to remote server.
      git: repo=git://github.com/newslynx/{{item}}.git 
           dest={{root_dir}}/{{item}} 
           accept_hostkey=true
      with_items: newslynx_repos

    - name: Create virtual environment.
      command: virtualenv --python=/usr/bin/python --no-site-packages {{python_env}}

    - name: Install Newslynx-Core Repos
      pip: name='.' chdir={{root_dir}}/{{item}}/ virtualenv={{python_env}}
      with_items: newslynx_repos

    - name: ensure the dot newslynx directory EXISTS
      file: "state=directory path=~/.newslynx/ mode=0777"

    - name: Copy Config Template
      template: src="templates/config.yaml.j2"
                dest="~/.newslynx/config.yaml"
                mode=0777

    - name: ensure the dot newslynx defaults directory EXISTS
      file: "state=directory path=~/.newslynx/defaults mode=0777"

    - name: Make defaults.
      command: "make defaults"
      args:
        chdir: "{{root_dir}}/newslynx-core/"
      when: incl_defaults

    # POSTGRES

    - name: ensure the pg mount directory EXISTS
      file: "state=directory path={{pg_mnt_point}} mode=0700 owner=postgres group=postgres"

    - name: stop postgres
      action: service name=postgresql state=stopped

    - name: Create a ext4 filesystem if a mounted drive is specified
      command: "mkfs.ext4 -F {{pg_mnt_path}}"
      when: pg_mnt_path is defined  

    - name: mount a drive if specified
      mount: "name={{pg_mnt_point}} src={{pg_mnt_path}} fstype=ext4 state=mounted"
      when: pg_mnt_path is defined

    - name: ensure the postgres data directory exists
      file: "state=directory path={{pg_dir}} mode=0700 owner=postgres group=postgres"

    - name: change the data directory to a mounted drive in pgconf
      lineinfile: dest={{pg_conf}} state=present regexp="^data_directory" line="data_directory=\'{{pg_dir}}\'"
      when: pg_mnt

    - name: change the data directory to a mounted drive in pgconf
      lineinfile: dest={{pg_conf}} state=present regexp="^data_directory" line="data_directory=\'{{pg_dir}}\'"
      when: pg_mnt

    - name: reconfigure the db with the new data directory
      command: "/usr/lib/postgresql/9.3/bin/initdb -D {{pg_dir}}"
      sudo: yes
      sudo_user: postgres

    - name: restart postgres
      action: service name=postgresql state=started

    - name: set postgres password
      command: psql -d postgres -U postgres -c "ALTER USER postgres with password '{{pg_password}}'"
      sudo: yes
      sudo_user: postgres

    - name: create newslynx db
      command: "psql -d postgres -U postgres -c 'CREATE DATABASE {{pg_name}}'"
      sudo: yes
      sudo_user: postgres

    - name: Initialize newslynx database.
      command: "{{python_env}}/bin/newslynx init"
      sudo: yes 
      args:
        chdir: "{{root_dir}}/newslynx-core/"

    # START SUPERVISOR PROCESSES

    - include: >
        supervisor.yaml 
        name=api
        exec="PSYCOGREEN=true {{python_env}}/bin/gunicorn newslynx.views:app -b 127.0.0.1:{{api_port}} -w {{api_workers}} -k gevent -t {{api_timeout}}"
        directory={{root_dir}}/newslynx-core
        user=root








