---
- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files:
    - vars/common.yaml
    - vars/newslynx-core.yaml
    - vars/newslynx-app.yaml
    - vars/postgres.yaml

  tasks:

    - name: restart app 
      command: "npm run forever-restart"
      args:
        chdir: "{{home}}/newslynx-app"
      sudo: yes

    # RESTART #
    - name: restart services
      service: name={{ item }} state=restarted
      with_items:
        - redis-server 
        - postgresql
        - supervisor
        - nginx 