---
- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files:
    - vars/common.yaml
    - vars/newslynx-core.yaml
    - vars/newslynx-app.yaml
    - vars/postgres.yaml

  tasks:

    # CORE #

    - name: pull newslynx-core
      command: "git pull origin {{core_branch}}"
      args:
        chdir: "{{home}}/newslynx-core/"
      sudo: yes

    - name: update configurations template
      template: 
      args:
        src: "templates/.newslynx/config.yaml.j2"
        dest: "~/.newslynx/config.yaml"
        mode: 0700
      sudo: yes

    - name: update newslynx-core
      command: make app_install 
      args:
        chdir: "{{home}}/newslynx-core/"

    # APP #

    - name: pull newslynx-app
      command: "git pull origin {{app_branch}}"
      args:
        chdir: "{{home}}/newslynx-app/"
      sudo: yes

    - name: update newslynx-app dependencies
      command: sudo npm install 
      args:
        chdir: "{{home}}/newslynx-app"
      sudo: yes

    - name: restart app 
      command: "npm run forever-restart"
      args:
        chdir: "{{home}}/newslynx-app"
      sudo: yes


    # RESTART #

    - name: restart redis + postgresql
      service: name={{ item }} state=restarted
      with_items:
        - redis-server 
        - postgresql 

    - name: restart supervisor 
      command: "service supervisor restart"
      sudo: yes
        - supervisor 

    - name: restart nginx
      service: name={{ item }} state=restarted
      with_items:
        - nginx
